#![cfg(test)]
#![allow(dead_code, unused_imports, unused_variables, unused_assignments)]

use crate::{keccak256, positional_merkle::*, Keccak256, Token};
use ethers::abi::{AbiEncode, Uint};
use forge_testsuite::Runner;
use primitive_types::{H256, U256};
use rand::Rng;
use rs_merkle::{merkelize_sorted, utils, MerkleProof, MerkleTree};
use std::{
    collections::{HashMap, HashSet},
    env, iter,
    path::PathBuf,
};

/// Converts an rs-merkle `MerkleProof` into the positioned `Node` format
/// expected by the Solidity `MerkleMultiProof` verifier.
///
/// Returns `(proof_nodes, leaf_nodes)` both sorted by position.
fn convert_rs_merkle_proof(
    proof: &MerkleProof<Keccak256>,
    leaf_indices: &[usize],
    leaf_hashes: &[[u8; 32]],
    total_leaves: usize,
) -> (Vec<Node>, Vec<Node>) {
    let height = utils::indices::tree_depth(total_leaves);

    // proof_indices_by_layers returns the 0-based indices that each proof hash
    // corresponds to, layer by layer (bottom-to-top), matching proof_hashes() order.
    // Convert each (layer, index) to a 1-based position and zip with the hashes.
    let proof_nodes = utils::indices::proof_indices_by_layers(leaf_indices, total_leaves)
        .into_iter()
        .enumerate()
        .flat_map(|(layer, indices)| {
            let level_start = 1usize << (height - layer);
            indices.into_iter().map(move |idx| level_start + idx)
        })
        .zip(proof.proof_hashes())
        .map(|(position, &hash)| Node { hash: H256(hash), position })
        .collect();

    // Convert leaf indices to positioned nodes
    let first_leaf_pos = 1usize << height;
    let mut leaf_nodes: Vec<Node> = leaf_indices
        .iter()
        .zip(leaf_hashes)
        .map(|(&i, hash)| Node { hash: H256(*hash), position: first_leaf_pos + i })
        .collect();
    leaf_nodes.sort_by_key(|n| n.position);

    (proof_nodes, leaf_nodes)
}

#[tokio::test(flavor = "multi_thread")]
async fn test_calculate_root() {
    let num_leaves = 600;
    let threshold = ((num_leaves * 1) / 3) - 1;
    dbg!(threshold);
    let leaves = (0..num_leaves).map(|_| H256::random().as_bytes().to_vec()).collect::<Vec<_>>();
    dbg!(leaves.len());
    let leaf_hashes = leaves.iter().map(keccak256).collect::<Vec<[u8; 32]>>();

    let tree = MerkleTree::<Keccak256>::from_leaves(&leaf_hashes);
    let mut rng = rand::thread_rng();
    let mut indices = std::collections::HashSet::new();
    while indices.len() < threshold {
        indices.insert(rng.gen_range(0..num_leaves));
    }
    let indices: Vec<usize> = indices.into_iter().collect();

    let positional_tree =
        PositionalMerkleTree::new(&leaf_hashes.clone().into_iter().map(H256).collect::<Vec<_>>())
            .unwrap();

    dbg!(positional_tree.root());

    let mut proof_items = vec![];

    for mut i in positional_tree.generate_multi_proof(&indices).unwrap().into_iter().rev() {
        i.sort_by_key(|node| node.position);
        proof_items.extend_from_slice(&i);
    }

    dbg!(proof_items.len());
    let height = tree_height(leaves.len() as u64);
    dbg!(height);

    let mut proof_leaves = indices
        .iter()
        .map(|&i| Node {
            hash: H256(leaf_hashes[i]),
            position: (2usize.pow((height) as u32) + i) as usize,
        })
        .collect::<Vec<_>>();
    proof_leaves.sort_by_key(|node| node.position);

    let root = calculate_balanced_root(&proof_items, &proof_leaves, leaves.len() as u64).unwrap();

    dbg!(root);
    assert_eq!(root, H256(tree.root().unwrap()));

    let base_dir = env::current_dir().unwrap().parent().unwrap().display().to_string();
    let mut runner = Runner::new(PathBuf::from(&base_dir));
    let mut contract = runner.deploy("MerkleMultiProofTest").await;

    let abi_leaves = proof_leaves
        .iter()
        .map(|i| {
            Token::Tuple(vec![
                Token::Uint(U256::from(i.position)),
                Token::FixedBytes(i.hash.0.to_vec()),
            ])
        })
        .collect::<Vec<_>>();

    let abi_proof = proof_items
        .into_iter()
        .map(|node| {
            Token::Tuple(vec![
                Token::Uint(U256::from(node.position)),
                Token::FixedBytes(node.hash.0.to_vec()),
            ])
        })
        .collect::<Vec<_>>();

    let calculated = contract
        .call::<_, [u8; 32]>(
            "CalculateRoot",
            (abi_proof.clone(), abi_leaves.clone(), Token::Uint(U256::from(leaves.len()))),
        )
        .await
        .unwrap();

    dbg!(H256(calculated));

    assert_eq!(root, H256(calculated));

    let beefy_root =
        binary_merkle_tree::merkle_root::<sp_runtime::traits::Keccak256, _>(leaves.clone());

    assert_eq!(beefy_root, H256(calculated));
}

/// Test that proofs generated by plain rs-merkle can be converted to the
/// positioned format and verified by the Solidity MerkleMultiProof contract.
#[tokio::test(flavor = "multi_thread")]
async fn test_rs_merkle_proof_conversion() {
    let num_leaves = 600;
    let threshold = ((num_leaves * 1) / 3) - 1;
    let leaves = (0..num_leaves).map(|_| H256::random().as_bytes().to_vec()).collect::<Vec<_>>();
    let leaf_hashes = leaves.iter().map(keccak256).collect::<Vec<[u8; 32]>>();

    let tree = MerkleTree::<Keccak256>::from_leaves(&leaf_hashes);

    // Pick random leaf indices to prove
    let mut rng = rand::thread_rng();
    let mut indices_set = HashSet::new();
    while indices_set.len() < threshold {
        indices_set.insert(rng.gen_range(0..num_leaves));
    }
    let mut indices: Vec<usize> = indices_set.into_iter().collect();
    indices.sort();

    // Generate proof using plain rs-merkle
    let rs_proof = tree.proof(&indices);
    let leaves_to_prove: Vec<[u8; 32]> = indices.iter().map(|&i| leaf_hashes[i]).collect();

    // Sanity: verify the proof works with rs-merkle's own verifier
    assert!(rs_proof.verify(tree.root().unwrap(), &indices, &leaves_to_prove, num_leaves));

    // Convert to positioned format for the Solidity verifier
    let (proof_nodes, leaf_nodes) =
        convert_rs_merkle_proof(&rs_proof, &indices, &leaves_to_prove, num_leaves);

    // Verify with the Rust reference implementation
    let root = calculate_balanced_root(&proof_nodes, &leaf_nodes, num_leaves as u64).unwrap();
    assert_eq!(root, H256(tree.root().unwrap()));

    // Verify with the Solidity contract
    let base_dir = env::current_dir().unwrap().parent().unwrap().display().to_string();
    let mut runner = Runner::new(PathBuf::from(&base_dir));
    let mut contract = runner.deploy("MerkleMultiProofTest").await;

    let abi_leaves = leaf_nodes
        .iter()
        .map(|n| {
            Token::Tuple(vec![
                Token::Uint(U256::from(n.position)),
                Token::FixedBytes(n.hash.0.to_vec()),
            ])
        })
        .collect::<Vec<_>>();

    let abi_proof = proof_nodes
        .into_iter()
        .map(|n| {
            Token::Tuple(vec![
                Token::Uint(U256::from(n.position)),
                Token::FixedBytes(n.hash.0.to_vec()),
            ])
        })
        .collect::<Vec<_>>();

    let calculated = contract
        .call::<_, [u8; 32]>(
            "CalculateRoot",
            (abi_proof, abi_leaves, Token::Uint(U256::from(num_leaves))),
        )
        .await
        .unwrap();

    assert_eq!(H256(tree.root().unwrap()), H256(calculated));
}
