#![cfg(test)]
#![allow(dead_code, unused_imports)]

use crate::{
    evm_runner::{project_root, EvmRunner},
    multi_proof_utils::{convert_rs_merkle_proof, Node},
    Keccak256,
};
use alloy_primitives::{keccak256, FixedBytes, U256};
use alloy_sol_types::{sol, SolCall};
use primitive_types::H256;
use proptest::{prop_assert, prop_assert_eq, prop_assert_ne, proptest};
use rand::Rng;
use rs_merkle::MerkleTree;
use std::collections::HashSet;

sol! {
    struct MpNode {
        uint256 position;
        bytes32 node;
    }

    function CalculateRoot(MpNode[] proof, MpNode[] leaves, uint256 numLeaves) external view returns (bytes32);
}

fn nodes_to_abi(nodes: &[Node]) -> Vec<MpNode> {
    nodes
        .iter()
        .map(|n| MpNode { position: U256::from(n.position), node: FixedBytes(n.hash.0) })
        .collect()
}

fn solidity_calculate_root(
    runner: &mut EvmRunner,
    contract: alloy_primitives::Address,
    proof_nodes: &[Node],
    leaf_nodes: &[Node],
    num_leaves: usize,
) -> H256 {
    let call = CalculateRootCall {
        proof: nodes_to_abi(proof_nodes),
        leaves: nodes_to_abi(leaf_nodes),
        numLeaves: U256::from(num_leaves),
    };

    let result = runner.call_raw(contract, call.abi_encode());
    let decoded = CalculateRootCall::abi_decode_returns(&result, true).unwrap();
    H256(decoded._0.0)
}

#[test]
fn test_calculate_root() {
    let num_leaves = 600;
    let threshold = ((num_leaves * 1) / 3) - 1;
    let leaves = (0..num_leaves).map(|_| H256::random().as_bytes().to_vec()).collect::<Vec<_>>();
    let leaf_hashes = leaves.iter().map(|l| keccak256(l).0).collect::<Vec<[u8; 32]>>();

    let tree = MerkleTree::<Keccak256>::from_leaves(&leaf_hashes);
    let mut rng = rand::thread_rng();
    let mut indices = HashSet::new();
    while indices.len() < threshold {
        indices.insert(rng.gen_range(0..num_leaves));
    }
    let mut indices: Vec<usize> = indices.into_iter().collect();
    indices.sort();

    let rs_proof = tree.proof(&indices);
    let leaves_to_prove: Vec<[u8; 32]> = indices.iter().map(|&i| leaf_hashes[i]).collect();

    assert!(rs_proof.verify(tree.root().unwrap(), &indices, &leaves_to_prove, num_leaves));

    let (proof_nodes, leaf_nodes) =
        convert_rs_merkle_proof(&rs_proof, &indices, &leaves_to_prove, num_leaves);

    let project = project_root();
    let mut runner = EvmRunner::new();
    let contract = runner.deploy(&project, "MerkleMultiProofTest");

    let calculated =
        solidity_calculate_root(&mut runner, contract, &proof_nodes, &leaf_nodes, leaves.len());

    assert_eq!(H256(tree.root().unwrap()), calculated);

    let beefy_root =
        binary_merkle_tree::merkle_root::<sp_runtime::traits::Keccak256, _>(leaves.clone());
    assert_eq!(beefy_root, calculated);
}

/// Test that proofs generated by plain rs-merkle can be converted to the
/// positioned format and verified by the Solidity MerkleMultiProof contract.
#[test]
fn test_rs_merkle_proof_conversion() {
    let num_leaves = 600;
    let threshold = ((num_leaves * 1) / 3) - 1;
    let leaves = (0..num_leaves).map(|_| H256::random().as_bytes().to_vec()).collect::<Vec<_>>();
    let leaf_hashes = leaves.iter().map(|l| keccak256(l).0).collect::<Vec<[u8; 32]>>();

    let tree = MerkleTree::<Keccak256>::from_leaves(&leaf_hashes);

    let mut rng = rand::thread_rng();
    let mut indices_set = HashSet::new();
    while indices_set.len() < threshold {
        indices_set.insert(rng.gen_range(0..num_leaves));
    }
    let mut indices: Vec<usize> = indices_set.into_iter().collect();
    indices.sort();

    let rs_proof = tree.proof(&indices);
    let leaves_to_prove: Vec<[u8; 32]> = indices.iter().map(|&i| leaf_hashes[i]).collect();

    assert!(rs_proof.verify(tree.root().unwrap(), &indices, &leaves_to_prove, num_leaves));

    let (proof_nodes, leaf_nodes) =
        convert_rs_merkle_proof(&rs_proof, &indices, &leaves_to_prove, num_leaves);

    let project = project_root();
    let mut runner = EvmRunner::new();
    let contract = runner.deploy(&project, "MerkleMultiProofTest");

    let calculated =
        solidity_calculate_root(&mut runner, contract, &proof_nodes, &leaf_nodes, num_leaves);

    assert_eq!(H256(tree.root().unwrap()), calculated);
}

/// Build a tree and single-leaf proof, return everything needed for Solidity verification.
fn build_multi_proof(
    num_leaves: usize,
    leaf_idx: usize,
) -> (
    [u8; 32],  // root
    Vec<Node>, // proof nodes
    Vec<Node>, // leaf nodes
    [u8; 32],  // leaf hash
) {
    let leaf_hashes: Vec<[u8; 32]> =
        (0..num_leaves).map(|i| keccak256(&(i as u32).to_le_bytes()).0).collect();
    let tree = MerkleTree::<Keccak256>::from_leaves(&leaf_hashes);
    let root = tree.root().unwrap();

    let proof = tree.proof(&[leaf_idx]);
    let (proof_nodes, leaf_nodes) =
        convert_rs_merkle_proof(&proof, &[leaf_idx], &[leaf_hashes[leaf_idx]], num_leaves);

    (root, proof_nodes, leaf_nodes, leaf_hashes[leaf_idx])
}

fn solidity_calc_root_raw(
    runner: &mut EvmRunner,
    contract: alloy_primitives::Address,
    proof_nodes: &[Node],
    leaf_nodes: &[Node],
    num_leaves: usize,
) -> Result<[u8; 32], String> {
    let call = CalculateRootCall {
        proof: nodes_to_abi(proof_nodes),
        leaves: nodes_to_abi(leaf_nodes),
        numLeaves: U256::from(num_leaves),
    };
    match runner.call_may_revert(contract, call.abi_encode()) {
        Ok(result) => {
            let decoded = CalculateRootCall::abi_decode_returns(&result, true)
                .map_err(|e| format!("decode: {e}"))?;
            Ok(decoded._0.0)
        },
        Err(e) => Err(e),
    }
}

proptest! {
    /// Random tree sizes and leaf selections must produce matching roots.
    #[test]
    fn test_random_multi_proof(
        num_leaves in 2usize..200,
        leaf_idx_raw in 0usize..200,
    ) {
        let leaf_idx = leaf_idx_raw % num_leaves;
        let (root, proof_nodes, leaf_nodes, _) = build_multi_proof(num_leaves, leaf_idx);

        let project = project_root();
        let mut runner = EvmRunner::new();
        let contract = runner.deploy(&project, "MerkleMultiProofTest");

        let calculated = solidity_calc_root_raw(&mut runner, contract, &proof_nodes, &leaf_nodes, num_leaves)
            .expect("CalculateRoot should not revert for valid proof");
        prop_assert_eq!(calculated, root);
    }

    /// Corrupted proof node hash must produce different root.
    #[test]
    fn test_corrupt_proof_node(
        num_leaves in 2usize..200,
        leaf_idx_raw in 0usize..200,
        byte_idx in 0usize..32,
    ) {
        let leaf_idx = leaf_idx_raw % num_leaves;
        let (root, mut proof_nodes, leaf_nodes, _) = build_multi_proof(num_leaves, leaf_idx);

        if proof_nodes.is_empty() { return Ok(()); }
        proof_nodes[0].hash.0[byte_idx] ^= 0xff;

        let project = project_root();
        let mut runner = EvmRunner::new();
        let contract = runner.deploy(&project, "MerkleMultiProofTest");

        match solidity_calc_root_raw(&mut runner, contract, &proof_nodes, &leaf_nodes, num_leaves) {
            Ok(calc) => prop_assert_ne!(calc, root, "corrupted proof matched root"),
            Err(_) => {} // revert is fine
        }
    }

    /// Corrupted leaf hash must produce different root.
    #[test]
    fn test_corrupt_leaf_hash(
        num_leaves in 2usize..200,
        leaf_idx_raw in 0usize..200,
        byte_idx in 0usize..32,
    ) {
        let leaf_idx = leaf_idx_raw % num_leaves;
        let (root, proof_nodes, mut leaf_nodes, _) = build_multi_proof(num_leaves, leaf_idx);

        leaf_nodes[0].hash.0[byte_idx] ^= 0xff;

        let project = project_root();
        let mut runner = EvmRunner::new();
        let contract = runner.deploy(&project, "MerkleMultiProofTest");

        match solidity_calc_root_raw(&mut runner, contract, &proof_nodes, &leaf_nodes, num_leaves) {
            Ok(calc) => prop_assert_ne!(calc, root, "forged leaf hash matched root"),
            Err(_) => {}
        }
    }

    /// Random replacement hash must produce different root.
    #[test]
    fn test_random_leaf_hash(
        num_leaves in 2usize..200,
        leaf_idx_raw in 0usize..200,
        fake_hash in proptest::array::uniform32(0u8..),
    ) {
        let leaf_idx = leaf_idx_raw % num_leaves;
        let (root, proof_nodes, mut leaf_nodes, real_hash) = build_multi_proof(num_leaves, leaf_idx);

        if fake_hash == real_hash { return Ok(()); }
        leaf_nodes[0].hash = H256(fake_hash);

        let project = project_root();
        let mut runner = EvmRunner::new();
        let contract = runner.deploy(&project, "MerkleMultiProofTest");

        match solidity_calc_root_raw(&mut runner, contract, &proof_nodes, &leaf_nodes, num_leaves) {
            Ok(calc) => prop_assert_ne!(calc, root, "random hash matched root"),
            Err(_) => {}
        }
    }

    /// OOB leaf position must not produce matching root.
    #[test]
    fn test_oob_leaf_position(
        num_leaves in 2usize..200,
        leaf_idx_raw in 0usize..200,
        offset in 1usize..256,
    ) {
        let leaf_idx = leaf_idx_raw % num_leaves;
        let (root, proof_nodes, mut leaf_nodes, _) = build_multi_proof(num_leaves, leaf_idx);

        let height = if num_leaves <= 1 { 0 } else { (usize::BITS - (num_leaves - 1).leading_zeros()) as usize };
        let max_pos = (1usize << height) + num_leaves - 1;
        leaf_nodes[0].position = max_pos + offset;

        let project = project_root();
        let mut runner = EvmRunner::new();
        let contract = runner.deploy(&project, "MerkleMultiProofTest");

        match solidity_calc_root_raw(&mut runner, contract, &proof_nodes, &leaf_nodes, num_leaves) {
            Ok(calc) => prop_assert_ne!(calc, root, "OOB position matched root"),
            Err(_) => {}
        }
    }

    /// Shifted leaf position must not produce matching root.
    #[test]
    fn test_shifted_leaf_position(
        num_leaves in 2usize..200,
        leaf_idx_raw in 0usize..200,
        delta in 1usize..5,
    ) {
        let leaf_idx = leaf_idx_raw % num_leaves;
        let (root, proof_nodes, mut leaf_nodes, _) = build_multi_proof(num_leaves, leaf_idx);

        let real_pos = leaf_nodes[0].position;
        let new_pos = if real_pos > delta { real_pos - delta } else { real_pos + delta };
        if new_pos == real_pos { return Ok(()); }
        leaf_nodes[0].position = new_pos;

        let project = project_root();
        let mut runner = EvmRunner::new();
        let contract = runner.deploy(&project, "MerkleMultiProofTest");

        match solidity_calc_root_raw(&mut runner, contract, &proof_nodes, &leaf_nodes, num_leaves) {
            Ok(calc) => prop_assert_ne!(calc, root, "shifted position matched root"),
            Err(_) => {}
        }
    }
}
