// Copyright (C) Polytope Labs Ltd.
// SPDX-License-Identifier: Apache-2.0

/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * 	http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
pragma solidity ^0.8.17;

import {Test, console} from "forge-std/Test.sol";
import {MerkleMountainRange} from "../../src/MerkleMountainRange.sol";
contract MerkleMountainRangeTest is Test {
    function setUp() public {}

    /*
     * This unit test showcases how to use the MMR contract
     * to verify a proof generated from the counterpart Rust library.
     */
    function testMerkleMountainRange() public {
        uint256 offset = 0;
        bytes32[] memory data = new bytes32[](5);
        MerkleMountainRange.HashIterator memory iterator = MerkleMountainRange.HashIterator(offset, data);

        // Define leaves values
        bytes32 value1 = bytes32(uint256(2));
        bytes32 value2 = bytes32(uint256(5));
        bytes32 value3 = bytes32(uint256(8));
        bytes32 value4 = bytes32(uint256(10));
        bytes32 value5 = bytes32(uint256(12));

        // Push the iterator to the MMR
        MerkleMountainRange._push(iterator, value1);
        MerkleMountainRange._push(iterator, value2);
        MerkleMountainRange._push(iterator, value3);
        MerkleMountainRange._push(iterator, value4);
        MerkleMountainRange._push(iterator, value5);

        assertEq(iterator.offset, 5);

        uint256 leafCount = 14;
        // Proof generated by `merkle_mountain_range.rs` implementation and converted to bytes32:
        bytes32[] memory proof = new bytes32[](7);
        proof[0] = 0xa4a7208a40e95acaf2fe1a3c675b1b5d8c341060e4f179b76ba79493582a95a6;
        proof[1] = 0x989a7025bda9312b19569d9e84e33a624e7fc007e54db23b6758d5f819647071;
        proof[2] = 0xfc5b56233029d71e7e9aff8e230ff491475dee2d8074b27d5fecf8f5154d7c8d;
        proof[3] = 0x37db026959b7bafb26c0d292ecd69c24df5eab845d9625ac5301324402938f25;
        proof[4] = 0x754310be011a7a378b07fa7cbac39dbedcadf645c518ddec58deeaa8c29e0634;
        proof[5] = 0x06be3c46e5a06d7b3e438a9d698f4319dc628624a63e484d97f00b92d09edce7;
        proof[6] = 0x7463c9b814b5d9081938e21346fe8bf81a9a9a0dcfa7bcc03b644a361e395a3b;

        // Leaves: Leaf(leafIndex, hash) — heap position is derived on-chain
        MerkleMountainRange.Leaf[] memory leaves = new MerkleMountainRange.Leaf[](5);
        leaves[0] = MerkleMountainRange.Leaf(2, 0x2b97a4b75a93aa1ac8581fac0f7d4ab42406569409a737bdf9de584903b372c5);
        leaves[1] = MerkleMountainRange.Leaf(5, 0xd279eb4bf22b2aeded31e65a126516215a9d93f83e3e425fdcd1a05ab347e535);
        leaves[2] = MerkleMountainRange.Leaf(8, 0x38e18ac9b4d78020e0f164d6da9ea61b962ab1975bcf6e8e80e9a9fc2ae509f8);
        leaves[3] = MerkleMountainRange.Leaf(10, 0x1a3930f70948f7eb1ceab07ecdb0967986091fd8b4b4f447406045431abd9795);
        leaves[4] = MerkleMountainRange.Leaf(12, 0xe54ccfb12a140c2dddb6cf78d1c6121610260412c66d00658ed1267863427ab9);

        // Check for calculated vs expected root.
        bytes32 root = CalculateRoot(proof, leaves, leafCount);
        console.logBytes32(root);
        bytes32 expectedRoot = 0x5aac4bad5c6a9014429b7e19ec0e5cd059d28d697c9cdd3f71e78cb6bfbd2600;
        assertEq(root, expectedRoot);

        // Verify the proof
        bool isValid = MerkleMountainRange.VerifyProof(expectedRoot, proof, leaves, leafCount);
        assertTrue(isValid);
    }

    /**
     * @notice Regression test: leaf index=1 with leafCount=1 previously bypassed the early-exit
     *         check, allowing arbitrary leaf hashes to pass verification. Now reverts with
     *         UnconsumedLeaves() because the leaf is never assigned to any peak subtree.
     */
    function testExploit_LeafIndexBypass() public {
        bytes32 knownRoot = 0x466dddba7e9a84a0f2632b59be71b8bd489e3334a1314a61253f8b827c9d3a36;

        bytes32[] memory proof = new bytes32[](1);
        proof[0] = knownRoot;

        MerkleMountainRange.Leaf[] memory leaves = new MerkleMountainRange.Leaf[](1);
        leaves[0] = MerkleMountainRange.Leaf(
            1,
            0xb870f0ca830d738b546237c54a050b892a1657766fae0786a412632ef318a99d
        );

        uint256 leafCount = 1;

        // After fix: CalculateRoot reverts because the leaf at index=1 is never
        // consumed by any peak subtree when leafCount=1
        vm.expectRevert(MerkleMountainRange.OutOfBoundsLeaves.selector);
        this.CalculateRoot(proof, leaves, leafCount);
    }

    /**
     * @notice Leaf index exceeds leafCount — leaf belongs to no subtree.
     *         Uses real leaf hash from testMerkleMountainRange but with index 100 (out of range for leafCount=14).
     */
    function testUnconsumedLeaves_IndexExceedsLeafCount() public {
        bytes32[] memory proof = new bytes32[](7);
        proof[0] = 0xa4a7208a40e95acaf2fe1a3c675b1b5d8c341060e4f179b76ba79493582a95a6;
        proof[1] = 0x989a7025bda9312b19569d9e84e33a624e7fc007e54db23b6758d5f819647071;
        proof[2] = 0xfc5b56233029d71e7e9aff8e230ff491475dee2d8074b27d5fecf8f5154d7c8d;
        proof[3] = 0x37db026959b7bafb26c0d292ecd69c24df5eab845d9625ac5301324402938f25;
        proof[4] = 0x754310be011a7a378b07fa7cbac39dbedcadf645c518ddec58deeaa8c29e0634;
        proof[5] = 0x06be3c46e5a06d7b3e438a9d698f4319dc628624a63e484d97f00b92d09edce7;
        proof[6] = 0x7463c9b814b5d9081938e21346fe8bf81a9a9a0dcfa7bcc03b644a361e395a3b;

        MerkleMountainRange.Leaf[] memory leaves = new MerkleMountainRange.Leaf[](1);
        leaves[0] = MerkleMountainRange.Leaf(100, 0x2b97a4b75a93aa1ac8581fac0f7d4ab42406569409a737bdf9de584903b372c5);

        vm.expectRevert(MerkleMountainRange.OutOfBoundsLeaves.selector);
        this.CalculateRoot(proof, leaves, 14);
    }

    /**
     * @notice Leaf index equals leafCount — off by one, still out of range.
     *         Index 14 is the first index past a 14-leaf MMR.
     */
    function testUnconsumedLeaves_IndexEqualsLeafCount() public {
        bytes32[] memory proof = new bytes32[](7);
        proof[0] = 0xa4a7208a40e95acaf2fe1a3c675b1b5d8c341060e4f179b76ba79493582a95a6;
        proof[1] = 0x989a7025bda9312b19569d9e84e33a624e7fc007e54db23b6758d5f819647071;
        proof[2] = 0xfc5b56233029d71e7e9aff8e230ff491475dee2d8074b27d5fecf8f5154d7c8d;
        proof[3] = 0x37db026959b7bafb26c0d292ecd69c24df5eab845d9625ac5301324402938f25;
        proof[4] = 0x754310be011a7a378b07fa7cbac39dbedcadf645c518ddec58deeaa8c29e0634;
        proof[5] = 0x06be3c46e5a06d7b3e438a9d698f4319dc628624a63e484d97f00b92d09edce7;
        proof[6] = 0x7463c9b814b5d9081938e21346fe8bf81a9a9a0dcfa7bcc03b644a361e395a3b;

        MerkleMountainRange.Leaf[] memory leaves = new MerkleMountainRange.Leaf[](1);
        leaves[0] = MerkleMountainRange.Leaf(14, 0xd279eb4bf22b2aeded31e65a126516215a9d93f83e3e425fdcd1a05ab347e535);

        vm.expectRevert(MerkleMountainRange.OutOfBoundsLeaves.selector);
        this.CalculateRoot(proof, leaves, 14);
    }

    /**
     * @notice Leaf index is max uint256 — never passes any subtree boundary check.
     */
    function testUnconsumedLeaves_MaxUint256Index() public {
        bytes32[] memory proof = new bytes32[](7);
        proof[0] = 0xa4a7208a40e95acaf2fe1a3c675b1b5d8c341060e4f179b76ba79493582a95a6;
        proof[1] = 0x989a7025bda9312b19569d9e84e33a624e7fc007e54db23b6758d5f819647071;
        proof[2] = 0xfc5b56233029d71e7e9aff8e230ff491475dee2d8074b27d5fecf8f5154d7c8d;
        proof[3] = 0x37db026959b7bafb26c0d292ecd69c24df5eab845d9625ac5301324402938f25;
        proof[4] = 0x754310be011a7a378b07fa7cbac39dbedcadf645c518ddec58deeaa8c29e0634;
        proof[5] = 0x06be3c46e5a06d7b3e438a9d698f4319dc628624a63e484d97f00b92d09edce7;
        proof[6] = 0x7463c9b814b5d9081938e21346fe8bf81a9a9a0dcfa7bcc03b644a361e395a3b;

        MerkleMountainRange.Leaf[] memory leaves = new MerkleMountainRange.Leaf[](1);
        leaves[0] = MerkleMountainRange.Leaf(type(uint256).max, 0x38e18ac9b4d78020e0f164d6da9ea61b962ab1975bcf6e8e80e9a9fc2ae509f8);

        vm.expectRevert(MerkleMountainRange.OutOfBoundsLeaves.selector);
        this.CalculateRoot(proof, leaves, 14);
    }

    /**
     * @notice Valid leaves from testMerkleMountainRange with one extra out-of-range leaf appended.
     *         The valid leaves compute correctly but leaf at index 50 is never consumed.
     */
    function testUnconsumedLeaves_MixedValidAndInvalid() public {
        bytes32[] memory proof = new bytes32[](7);
        proof[0] = 0xa4a7208a40e95acaf2fe1a3c675b1b5d8c341060e4f179b76ba79493582a95a6;
        proof[1] = 0x989a7025bda9312b19569d9e84e33a624e7fc007e54db23b6758d5f819647071;
        proof[2] = 0xfc5b56233029d71e7e9aff8e230ff491475dee2d8074b27d5fecf8f5154d7c8d;
        proof[3] = 0x37db026959b7bafb26c0d292ecd69c24df5eab845d9625ac5301324402938f25;
        proof[4] = 0x754310be011a7a378b07fa7cbac39dbedcadf645c518ddec58deeaa8c29e0634;
        proof[5] = 0x06be3c46e5a06d7b3e438a9d698f4319dc628624a63e484d97f00b92d09edce7;
        proof[6] = 0x7463c9b814b5d9081938e21346fe8bf81a9a9a0dcfa7bcc03b644a361e395a3b;

        MerkleMountainRange.Leaf[] memory leaves = new MerkleMountainRange.Leaf[](6);
        leaves[0] = MerkleMountainRange.Leaf(2, 0x2b97a4b75a93aa1ac8581fac0f7d4ab42406569409a737bdf9de584903b372c5);
        leaves[1] = MerkleMountainRange.Leaf(5, 0xd279eb4bf22b2aeded31e65a126516215a9d93f83e3e425fdcd1a05ab347e535);
        leaves[2] = MerkleMountainRange.Leaf(8, 0x38e18ac9b4d78020e0f164d6da9ea61b962ab1975bcf6e8e80e9a9fc2ae509f8);
        leaves[3] = MerkleMountainRange.Leaf(10, 0x1a3930f70948f7eb1ceab07ecdb0967986091fd8b4b4f447406045431abd9795);
        leaves[4] = MerkleMountainRange.Leaf(12, 0xe54ccfb12a140c2dddb6cf78d1c6121610260412c66d00658ed1267863427ab9);
        leaves[5] = MerkleMountainRange.Leaf(50, 0xe54ccfb12a140c2dddb6cf78d1c6121610260412c66d00658ed1267863427ab9);

        vm.expectRevert(MerkleMountainRange.OutOfBoundsLeaves.selector);
        this.CalculateRoot(proof, leaves, 14);
    }

    function VerifyProof(bytes32 root, bytes32[] memory proof, MerkleMountainRange.Leaf[] memory leaves, uint256 leafCount)
        public
        pure
        returns (bool)
    {
        return MerkleMountainRange.VerifyProof(root, proof, leaves, leafCount);
    }

    function CalculateRoot(bytes32[] memory proof, MerkleMountainRange.Leaf[] memory leaves, uint256 leafCount)
        public
        pure
        returns (bytes32)
    {
        return MerkleMountainRange.CalculateRoot(proof, leaves, leafCount);
    }
}
